#:schema node_modules/wrangler/config-schema.json
name = "hoopadvisors-website"
main = "./index.js"
compatibility_date = "2024-10-11"
assets = { directory = "./public" }

routes = [
  { pattern = "hoopadvisors.com", custom_domain = true }
]

[vars]
SECRET_KEY = "qz+/vZ3ZBxC3aAZ4a5brJuimOaJUVbsq825PVb/ZprI="
ACCESS_CODE = "b@ll"

[[durable_objects.bindings]]
name = "WEBSOCKET_SERVER"
class_name = "WebsocketServer"

[[durable_objects.bindings]]
name = "GAME_SERVER"
class_name = "GameServer"

[[migrations]]
tag = "v1"
new_classes = ["GameServer", "WebsocketServer"]

[observability]
enabled = true

[[services]]
binding = "scrapers"
service = "hoopadvisors-scrapers"

[limits]
cpu_ms = 300_000