#:schema node_modules/wrangler/config-schema.json
name = "hoopadvisors"
main = "src/index.js"
compatibility_date = "2024-10-11"
assets = { directory = "./public" }

[[durable_objects.bindings]]
name = "SERVER"
class_name = "Server"

[[migrations]]
tag = "v1"
new_classes = ["Server"]
