#:schema node_modules/wrangler/config-schema.json
name = "hoopadvisors"
main = "./index.js"
compatibility_date = "2024-10-11"
assets = { directory = "./public" }

[vars]
SECRET_KEY = "qz+/vZ3ZBxC3aAZ4a5brJuimOaJUVbsq825PVb/ZprI="
ACCESS_CODE = "b@ll"

[[durable_objects.bindings]]
name = "SERVER"
class_name = "Server"

[[migrations]]
tag = "v1"
new_classes = ["Server"]
